### ISSUE TITLE
Make class instead of closure on the decorator

### ISSUE THREAD

**Issue by pjanowski** [Azure/confidential-ml-utils#29]
Required for HDI/Spark. See implementation here

https://eemo.visualstudio.com/TEE/_git/TEEGit?path=%2FOffline%2FFocusedInbox%2FComTriage%2Fcomtriage%2Futils%2Fscrubber.py&version=GBcompliant%2FComTriage&_a=contents

**Comment by dkmiller** [comment]
Comment from Dan S.:

> Any decorator on a udf needs to be pickleable, so when you make the outer function that takes arguments and returns the decorator, that decorator is not pickleable, but if instead of using a function with a closure to capture arguments, you can make a class to store the arguments and make the call function of the class return the wrapper. That makes it pickleable
