### ISSUE TITLE
logger does not override the log method

### ISSUE THREAD

**Issue by danrsc** [Azure/confidential-ml-utils#56]
If you call logger.log on ConfidentialLogger, then it is currently routed to the superclass definition of log, which in turn will call the ConfidentialLogger._log method. The ConfidentialLogger._log method has a different signature than the superclass _log method, so this call ends up breaking

**Comment by danrsc** [comment]
This is mitigated by https://github.com/Azure/confidential-ml-utils/pull/58/files
I would still like to have a method which acts like log, but I can see why you might not want to override the log method.
Could we have a logx (or some better name) method that is like log but takes category?

**Comment by dkmiller** [comment]
Some context:

https://www.python.org/dev/peps/pep-3102/

Consensus: add some tests with non-category aware OSS libraries, ensure that those work.

Align on signature with base classes, change `category` to be a keyword-only argument.

**Comment by danrsc** [comment]
The issue is actually broader than indicated here. Any non-category aware code that calls logging.getLogger() can then call any of the functions that would normally be called on the logger: log, info, warn, debug etc.
At the moment the ConfidentialLogger has different signatures for all of these methods, so if the non-category aware code passes parameters positionally, the result will be broken. We should match all of the signatures to the base class since we are replacing the root logger, and use a keyword-only argument for the category extension.
Implementing a category-aware version of log would also be nice
